version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: dockerfile
    container_name: auth-local
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - STORAGE_S3_NAME_SPACE=${STORAGE_S3_NAME_SPACE}
      - STORAGE_S3_ACCESS_KEY=${STORAGE_S3_ACCESS_KEY}
      - STORAGE_S3_SECRET_KEY=${STORAGE_S3_SECRET_KEY}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    volumes:
      - ./uploads:/app/uploads
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge
