version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - auth-prod
      - auth-dev
    networks:
      - auth-network

  auth-prod:
    image: ghcr.io/SEU_USUARIO/SEU_REPOSITORIO:latest
    container_name: auth-prod
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - STORAGE_S3_NAME_SPACE=${STORAGE_S3_NAME_SPACE}
      - STORAGE_S3_ACCESS_KEY=${STORAGE_S3_ACCESS_KEY}
      - STORAGE_S3_SECRET_KEY=${STORAGE_S3_SECRET_KEY}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    volumes:
      - /var/app/uploads:/app/uploads
    networks:
      - auth-network

  auth-dev:
    image: ghcr.io/SEU_USUARIO/SEU_REPOSITORIO:develop
    container_name: auth-dev
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - STORAGE_S3_NAME_SPACE=${STORAGE_S3_NAME_SPACE}
      - STORAGE_S3_ACCESS_KEY=${STORAGE_S3_ACCESS_KEY}
      - STORAGE_S3_SECRET_KEY=${STORAGE_S3_SECRET_KEY}
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    volumes:
      - /var/app/uploads-dev:/app/uploads
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge
