name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build application
      run: mvn clean package -DskipTests

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        port: ${{ secrets.VPS_PORT }}
        script: |
          # Baixar e executar script de deploy
          curl -fsSL https://raw.githubusercontent.com/jeronimo0007/auth-java-erp/main/scripts/deploy-prod-fixed.sh -o deploy-prod.sh
          chmod +x deploy-prod.sh
          
          # Executar deploy
          GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" \
          GITHUB_ACTOR="${{ github.actor }}" \
          DB_URL="${{ secrets.DB_URL }}" \
          DB_USERNAME="${{ secrets.DB_USERNAME }}" \
          DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
          JWT_SECRET="${{ secrets.JWT_SECRET }}" \
          JWT_EXPIRATION="${{ secrets.JWT_EXPIRATION }}" \
          STORAGE_S3_NAME_SPACE="${{ secrets.STORAGE_S3_NAME_SPACE }}" \
          STORAGE_S3_ACCESS_KEY="${{ secrets.STORAGE_S3_ACCESS_KEY }}" \
          STORAGE_S3_SECRET_KEY="${{ secrets.STORAGE_S3_SECRET_KEY }}" \
          RABBITMQ_HOST="${{ secrets.RABBITMQ_HOST }}" \
          RABBITMQ_USERNAME="${{ secrets.RABBITMQ_USERNAME }}" \
          RABBITMQ_PASSWORD="${{ secrets.RABBITMQ_PASSWORD }}" \
          ./deploy-prod.sh
